AWSTemplateFormatVersion: 2010-09-09
Description: Academy Demo Template

Parameters:
  QueName:
    Description : Name for queue
    Type : String
    Default: demo-que-academy-asd
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket