AWSTemplateFormatVersion: 2010-09-09
Description: Academy Demo Template
Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  IrelandDefaultVPC:
    Type: String
    Default: vpc-32cc224b
  IrelandDefaultSubnetA:
    Type: String
    Default: subnet-1e035878
  IrelandDefaultSubnetB:
    Type: String
    Default: subnet-018ba049
  IrelandDefaultSubnetC:
    Type: String
    Default: subnet-b984e1e3

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
  MyQueue:
    Type: AWS::SQS::Queue
  SaanaInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SaanaInstanceSecurityGroup
  SaanaLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      Subnets:
        - !Ref IrelandDefaultSubnetA
        - !Ref IrelandDefaultSubnetB
        - !Ref IrelandDefaultSubnetC
      SecurityGroups:
        - !Ref SaanaLoadBalancerSecurityGroup
  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref SaanaLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup
  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref IrelandDefaultVPC
      Port: 80
      Protocol: HTTP
  SaanaInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
       GroupDescription: 'Security group for EC2 instance'
       SecurityGroupIngress:
         - IpProtocol: tcp
           FromPort: '80'
           ToPort: '80'
           SourceSecurityGroupId: !Ref SaanaLoadBalancerSecurityGroup
  SaanaLoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ELB scgroup
      VpcId: vpc-32cc224b
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
Outputs:
  LoadBalancer:
     Description: A reference to the Application Load Balancer
     Value: !Ref SaanaLoadBalancer